name: Compile-test-amd64

on:
  push:
    branches: [ "develop", "master" ]
  
  pull_request:
    branches: [ "master" ]

jobs:
  Compile-ego-planner-swarm-amd64:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Start to Compile
      run: ./scripts/compile/compile.sh amd64

